# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  fzf
  fasd
  tmux
  tmuxinator
  ls
)

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
path=(
  $path
  $HOME/.dotfiles/bin
  $HOME/.poetry/bin
  $HOME/.pyenv/bin
  $HOME/bin
  /usr/local/bin
  /usr/local/opt/ruby/bin
)

# export
export EDITOR='vim'

# ZSH Powerlevel10k configuration
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# ZSH configuration
ZSH_DISABLE_COMPFIX="true"
ZSH_THEME="powerlevel10k/powerlevel10k"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="true"
DISABLE_MAGIC_FUNCTIONS="true" # required for fast pastes

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# alias
alias e='vim'
alias mux="tmuxinator"

# pyenv 
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# custom functions
function cd {
    builtin cd "$@" && ls -1
}

# use vimode
# bindkey -v
