# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/hunjae/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  tmux
  fasd
)

path=(
  $path
  $HOME/.dotfiles/bin
  $HOME/Library/Android/sdk/platform-tools
)

autoload -U promptinit; promptinit
prompt pure

eval "$(fasd --init auto)"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/hunjae/.pyenv/versions/anaconda3-2019.10/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/hunjae/.pyenv/versions/anaconda3-2019.10/etc/profile.d/conda.sh" ]; then
#        . "/Users/hunjae/.pyenv/versions/anaconda3-2019.10/etc/profile.d/conda.sh"
#    else
#        export PATH="/Users/hunjae/.pyenv/versions/anaconda3-2019.10/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<

# neovim
alias e='vim'
#alias vi='nvim'
#alias vim='nvim'
#alias vimdiff="nvim -d"
export EDITOR=/usr/local/bin/nvim

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/opt/ruby/bin:$PATH"

export LC_ALL=en_US.UTF-8

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line

bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
